#!/bin/bash

echo -e "\033[46;1;37m---------------------------------------"
echo -e " Script Extreme By Cosmo               "
echo -e "                                       "
echo -e " Repositórios e atualização do sistema "
echo -e "---------------------------------------\033[0m"
echo " - "
echo " - "
echo " - "

#themes e icons

 add_repositorios (){
  echo " "
  echo -e "\033[1;33m-= Adicionando repositorios =-\033[0m"
  sudo add-apt-repository ppa:noobslab/themes -y  2> /dev/null
  sudo add-apt-repository ppa:numix/ppa -y  2> /dev/null
  sudo add-apt-repository -y ppa:nilarimogard/webupd8 -y  2> /dev/null
  sudo add-apt-repository ppa:videolan/stable-daily -y  2> /dev/null
  sudo add-apt-repository ppa:rvm/smplayer -y  2> /dev/null
  sudo add-apt-repository ppa:inkscape.dev/stable -y  2> /dev/null
  sudo add-apt-repository ppa:otto-kesselgulasch/gimp -y  2> /dev/null
  sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable -y  2> /dev/null
  sudo add-apt-repository ppa:gezakovacs/ppa -y  2> /dev/null
  sudo add-apt-repository ppa:libreoffice/ppa -y  2> /dev/null
  sudo add-apt-repository ppa:webupd8team/atom -y  2> /dev/null
  sudo add-apt-repository -y ppa:webupd8team/sublime-text-3 -y  2> /dev/null
  sudo add-apt-repository ppa:webupd8team/java -y  2> /dev/null
  sudo add-apt-repository ppa:ricotz/docky -y  2> /dev/null

  #atualiza o sistema
  atualizar_sistema
 }



#atualiza os novos repositorios e atualizações do sistema

  atualizar_sistema () {
    echo " "
    echo -e "\033[1;33m-= Atualizando o sistema =-\033[0m"
    sudo apt-get update  2> /dev/null  > /dev/null
    sudo apt-get upgrade -y  2> /dev/null
  }



#tradução para o português

 language_pt (){
  echo " "
  echo -e "\033[1;33m-= Language PT_BR =-\033[0m"
  sudo apt-get -f install language-pack-gnome-pt language-pack-pt-base -y 2> /dev/null
}

#executa as instalações do programas

  instalador (){

  echo " "
  echo -e "\033[1;33m-= Instalador de programas =-\033[0m"

  sudo apt-get -f install numix-icon-theme numix-icon-theme-circle royal-gtk-theme -y  2> /dev/null
  sudo apt-get -f install audacious audacious-plugins -y  2> /dev/null
  sudo apt-get -f install vlc -y  2> /dev/null
  sudo apt-get -f install smplayer smplayer-skins smplayer-themes -y  2> /dev/null
  sudo apt-get -f install ubuntu-restricted-extras -y
  sudo apt-get -f install unace unrar zip unzip p7zip-full p7zip-rar sharutils -y  2> /dev/null
  sudo apt-get -f install unetbootin -y  2> /dev/null
  sudo apt-get -f install qbittorrent -y  2> /dev/null
  sudo apt-get -f install gdebi -y  2> /dev/null
  sudo apt-get -f install synaptic -y  2> /dev/null
  sudo apt-get -f install samba samba-common system-config-samba python-glade2 gksu -y  2> /dev/null
  sudo apt-get -f install gparted -y  2> /dev/null
  sudo apt-get -f install docky -y  2> /dev/null
  sudo apt-get -f install chromium-browser-y  2> /dev/null
  sudo apt-get -f install gimp -y  2> /dev/null
  sudo apt-get -f install inkscape -y  2> /dev/null
  sudo apt-get -f install libreoffice -y
  sudo apt-get -f install gedit -y  2> /dev/null
  sudo apt-get -f install atom -y  2> /dev/null
  sudo apt-get -f install sublime-text-installer -y  2> /dev/null

  sudo apt-get purge openjdk* -y
  sudo apt-get install oracle-java8-installer -y
  sudo apt-get install oracle-java8-set-default -y

  }






if [ "$UID" -ne 0 ]
then
echo -e "\033[0;31m|-----------------------------------------------|"
echo -e " "
echo -e "  Executar o script $0"
echo -e "  com sudo ou root."
echo -e " "
echo -e "|-----------------------------------------------|\033[0m"
exit
fi

if uname -a | grep -i ubuntu  | grep -i 14.04 2> /dev/null > /dev/null
then
echo "Versão OK!"
lsb_release -d

atualizar_sistema

#add_repositorios
exit
fi
